[project]
name = "mal-ls"
version = "0.1.0"
description = "Language server for MAL"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.11.10",
]

authors = { "Tobiky" = "me@tobiky.dev" }
urls = { github = "https://github.com/Tobiky/mal-ls" }

[project.scripts]
mal-ls = "mal-ls.__main__:main"

