name: Language Server Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  
jobs:
  language-server-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          enable-cache: true

      - name: Update uv.lock (if needed)
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        if: success() && hashFiles('tests/**') != ''
        run: uv run pytest
