name: Language Server Tests

on:
  pull_request:
    branches: [ "master" ]
  
jobs:
  language-server-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          enable-cache: true

      - name: Update uv.lock (if needed)
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        if: success() && hashFiles('tests/**') != ''
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes
        # Limit step run-time to 3 minutes
        timeout-minutes: 3
        run: uv run pytest
